language: cpp
compiler: gcc
env:
    - PROTOBUF_VERSION=2.6.0
install:
    - sudo apt-get install libboost-dev
    - wget https://github.com/google/protobuf/releases/download/v2.6.0/protobuf-2.6.0.tar.gz
    - tar xf protobuf-2.6.0.tar.gz
    - ( cd protobuf-$PROTOBUF_VERSION && ./configure && make -j4 && sudo make install && sudo ldconfig )
    - git clone https://github.com/google/snappy
    - ( cd snappy && sh ./autogen.sh && ./configure && make -j2 && sudo make install )
    - sudo apt-get install zlib1g-dev
    - git clone https://github.com/koalademo/sofa-pbrpc ./third_party/sofa-pbrpc
    - ( cd third_party/sofa-pbrpc && make proto && make -j4 && make install);
script: make proto
